import { env } from "$env/dynamic/private"
import type { AppConfig } from "$lib/types/app-config"
import {
	MISTRAL_DEFAULT_SUPPORTED_MESSAGE_FILE_MIME_TYPES,
	MISTRAL_DEFAULT_SUPPORTED_MESSAGE_IMAGE_MIME_TYPES,
	OPEN_AI_DEFAULT_SUPPORTED_MESSAGE_FILE_MIME_TYPES,
	OPEN_AI_DEFAULT_SUPPORTED_MESSAGE_IMAGE_MIME_TYPES
} from "./supported-mime-types"

export const APP_CONFIG: AppConfig = {
	NAME: env.APP_NAME || "Mugin",
	BODY_SIZE_LIMIT_BYTES: env.BODY_SIZE_LIMIT?.endsWith("M") ? Number(env.BODY_SIZE_LIMIT.split("M")[0]) * 1024 * 1024 : 10 * 1024 * 1024,
	APP_ROLES: {
		ADMIN: env.APP_ROLE_ADMIN as string,
		AGENT_MAINTAINER: env.APP_ROLE_AGENT_MAINTAINER as string,
		EMPLOYEE: env.APP_ROLE_EMPLOYEE as string,
		STUDENT: env.APP_ROLE_STUDENT as string,
		EDU_EMPLOYEE: env.APP_ROLE_EDU_EMPLOYEE || "eduemployee"
	},
	NEW_CHAT_CONFIRM_DISABLED: env.NEW_CHAT_CONFIRM_DISABLED === "true",
	TRANSCRIPTION_GROUPS: (() => {
		const groups = []
		let n = 1
		while (env[`TRANSCRIPTION_GROUP_${n}_ID`]) {
			groups.push({
				id: env[`TRANSCRIPTION_GROUP_${n}_ID`] as string,
				label: env[`TRANSCRIPTION_GROUP_${n}_LABEL`] ?? `Group ${n}`
			})
			n++
		}
		return groups
	})(),
	VENDORS: {
		MISTRAL: {
			NAME: "Mistral",
			ENABLED: Boolean(env.MISTRAL_API_KEY_PROJECT_DEFAULT),
			PROJECTS: Object.keys(env)
				.filter((key) => key.startsWith("MISTRAL_API_KEY_PROJECT"))
				.map((key) => key.replace("MISTRAL_API_KEY_PROJECT_", "")),
			SUPPORTED_MESSAGE_FILE_MIME_TYPES: MISTRAL_DEFAULT_SUPPORTED_MESSAGE_FILE_MIME_TYPES,
			SUPPORTED_MESSAGE_IMAGE_MIME_TYPES: MISTRAL_DEFAULT_SUPPORTED_MESSAGE_IMAGE_MIME_TYPES
		},
		OPENAI: {
			NAME: "OpenAI",
			ENABLED: Boolean(env.OPENAI_API_KEY_PROJECT_DEFAULT),
			PROJECTS: Object.keys(env)
				.filter((key) => key.startsWith("OPENAI_API_KEY_PROJECT"))
				.map((key) => key.replace("OPENAI_API_KEY_PROJECT_", "")),
			SUPPORTED_MESSAGE_FILE_MIME_TYPES: OPEN_AI_DEFAULT_SUPPORTED_MESSAGE_FILE_MIME_TYPES,
			SUPPORTED_MESSAGE_IMAGE_MIME_TYPES: OPEN_AI_DEFAULT_SUPPORTED_MESSAGE_IMAGE_MIME_TYPES
		},
		OLLAMA: {
			NAME: "Ollama",
			ENABLED: Boolean(env.OLLAMA_HOST),
			PROJECTS: ["DEFAULT"],
			SUPPORTED_MESSAGE_FILE_MIME_TYPES: [],
			SUPPORTED_MESSAGE_IMAGE_MIME_TYPES: []
		},
		LITELLM: {
			NAME: "Telemark fylkeskommune",
			ENABLED: Boolean(env.LITELLM_BASE_URL),
			PROJECTS: ["DEFAULT"],
			SUPPORTED_MESSAGE_FILE_MIME_TYPES: [],
			SUPPORTED_MESSAGE_IMAGE_MIME_TYPES: []
		}
	}
}
